# Generated by Django 5.2.15 on 2026-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='jd_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeevaluation',
            name='matched_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeevaluation',
            name='status',
            field=models.CharField(default='Review', max_length=40),
        ),
    ]
