# Generated by Django 5.2.15 on 2026-06-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_jobopening_extracted_skills_jobopening_jd_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='bulk_resumes/')),
                ('file_name', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('match_percentage', models.PositiveIntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='Review', max_length=40)),
                ('ai_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_resume_uploads', to='recruitment.jobopening')),
            ],
        ),
    ]
