# Generated by Django 5.2.15 on 2026-06-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_bulkresumeupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='stored_resumes/')),
                ('file_name', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
