# Generated by Django 5.2.15 on 2026-06-06 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_storedresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedresume',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ResumeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.PositiveIntegerField(default=0)),
                ('recommendation', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='Review', max_length=40)),
                ('analysis', models.TextField(blank=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to='recruitment.jobopening')),
                ('stored_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='recruitment.storedresume')),
            ],
            options={
                'unique_together': {('job_opening', 'stored_resume')},
            },
        ),
    ]
