# Generated by Django 5.2.15 on 2026-06-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_storedresume_file_hash_resumematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='answer_reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_recommendation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='final_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='recruitment.candidate'),
        ),
    ]
